In [1]:
# --- imports ---
import os
from dotenv import load_dotenv

import pandas as pd
from sqlalchemy import create_engine, text

In [2]:
file_path = "../data/insurance_claims_dataset.csv"
df = pd.read_csv(file_path)
display(df.head())

# standardize all column names into lowercase
# for easier processing
df.columns = [col.lower().strip() for col in df.columns]
display(df.head())

,Claim_ID,Customer_ID,Policy_Number,Age,Gender,Region,Policy_Type,Premium_Amount,Coverage_Amount,Claim_Amount,Claim_Type,Credit_Score,Fraud_Risk_Score,Fraud_Flag,Claim_Status,Settlement_Amount
0,CLM000001,CUST018311,POL0285346,79,Male,West,Home,3264.23,56380.37,8140.64,Accident,529,91.93,Yes,Under Review,4330.86
1,CLM000002,CUST003854,POL0518267,78,Female,West,Home,4937.85,98556.51,32997.15,Accident,331,82.90,Yes,Under Review,30106.34
2,CLM000003,CUST018067,POL0278802,57,Male,West,Health,3952.90,33481.54,14873.17,Property,642,30.69,No,Approved,10424.77
3,CLM000004,CUST007487,POL0372362,66,Male,North,Health,579.12,24701.69,616.78,Property,411,68.15,No,Approved,431.01
4,CLM000005,CUST011899,POL0882135,21,Female,East,Home,676.23,28416.22,42049.70,Theft,714,45.04,No,Approved,27957.75

,claim_id,customer_id,policy_number,age,gender,region,policy_type,premium_amount,coverage_amount,claim_amount,claim_type,credit_score,fraud_risk_score,fraud_flag,claim_status,settlement_amount
0,CLM000001,CUST018311,POL0285346,79,Male,West,Home,3264.23,56380.37,8140.64,Accident,529,91.93,Yes,Under Review,4330.86
1,CLM000002,CUST003854,POL0518267,78,Female,West,Home,4937.85,98556.51,32997.15,Accident,331,82.90,Yes,Under Review,30106.34
2,CLM000003,CUST018067,POL0278802,57,Male,West,Health,3952.90,33481.54,14873.17,Property,642,30.69,No,Approved,10424.77
3,CLM000004,CUST007487,POL0372362,66,Male,North,Health,579.12,24701.69,616.78,Property,411,68.15,No,Approved,431.01
4,CLM000005,CUST011899,POL0882135,21,Female,East,Home,676.23,28416.22,42049.70,Theft,714,45.04,No,Approved,27957.75

In [3]:
df.shape

(50000, 16)

In [4]:
# connect to client
load_dotenv(dotenv_path='../.env')
db_password = os.getenv('DB_PASSWORD')
db_name = 'insurance_fraud'

engine = create_engine(f'postgresql://postgres:{db_password}@localhost:5432/{db_name}')

with engine.begin() as conn:
    conn.execute(text("DROP VIEW IF EXISTS claims_triage_view"))

df.to_sql(name='insurance_claims', con=engine, if_exists='replace', index=False)
print("Successfully uploaded.")

Successfully uploaded.